# This file is used by Copier to track the template version
# and enable template updates in generated projects

_commit: d439e067d6a4a123dc84d1c27642e2cd03356d67
_src_path: gh:stateful-y/python-package-copier
author_email: gtauzin@stateful-y.io
author_name: Guillaume Tauzin
description: An Optuna integration for hyperparameter tuning in Scikit-Learn
github_username: stateful-y
include_actions: True
include_examples: True
license: Apache-2.0
max_python_version: '3.14'
min_python_version: '3.11'
package_name: sklearn_optuna
project_name: Sklearn-Optuna
project_slug: sklearn-optuna
